# Entrega DataSets

In [1]:
import pandas as pd

1.- Diabetes (Kaggle)

In [2]:
dts_1 = pd.read_csv('diabetes_health_indicators_2015.csv', sep = ',')

In [3]:
dts_1

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,2.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,2.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

2.- Bitcoin (Kaggle)

In [8]:
dts_2 = pd.read_csv('bitcoin.csv', sep = ',')

In [9]:
dts_2

,Open Time,Open,High,Low,Close,Volume,Close Time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume
0,1609459200000,28923.63,28961.66,28913.12,28961.66,27.457032,1609459259999,7.943820e+05,1292,16.777195,485390.826825
1,1609459260000,28961.67,29017.50,28961.01,29009.91,58.477501,1609459319999,1.695803e+06,1651,33.733818,978176.468202
2,1609459320000,29009.54,29016.71,28973.58,28989.30,42.470329,1609459379999,1.231359e+06,986,13.247444,384076.854453
3,1609459380000,28989.68,28999.85,28972.33,28982.69,30.360677,1609459439999,8.800168e+05,959,9.456028,274083.075142
4,1609459440000,28982.67,28995.93,28971.80,28975.65,24.124339,1609459499999,6.992262e+05,726,6.814644,197519.374888
...,...,...,...,...,...,...,...,...,...,...,...
188312,1620794100000,57517.42,57526.28,57485.00,57485.07,42.575735,1620794159999,2.448258e+06,1195,15.319691,880913.090845
188313,1620794160000,57485.07,57496.42,57466.75,57481.49,34.205467,1620794219999,1.966194e+06,1096,15.971891,918058.816162
188314,1620794220000,57477.18,57509.99,57458.18,57470.00,30.211789,1620794279999,1.736514e+06,955,13.054229,750364.577319
188315,1620794280000,57470.00,57470.01,57400.00,57450.90,45.354728,1620794339999,2.605080e+06,1559,12.615628,724559.233035
188316,1620794340000,57450.89,57475.66,57435.51,57450.19,14.168318,1620794399999,8.140594e+05,730,7.247751,416412.022206

3.- Canciones TikTok 2019 (Kaggle)

In [6]:
dts_3 = pd.read_csv('TikTok_songs_2019.csv', sep = ',')

In [7]:
dts_3

,track_name,artist_name,artist_pop,album,track_pop,danceability,energy,loudness,mode,key,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,duration_ms
0,Shake It,Metro Station,53,Metro Station,68,0.618,0.955,-3.836,1,4,0.0798,0.00221,0.000003,0.4860,0.790,150.034,4,179947
1,Chinese New Year,SALES,61,SALES - EP,53,0.744,0.845,-7.422,0,4,0.2530,0.75900,0.232000,0.1000,0.749,75.221,4,160000
2,Baby I'm Yours,Breakbot,57,By Your Side,69,0.829,0.792,-3.755,0,2,0.0668,0.72600,0.000006,0.1220,0.758,118.050,4,215507
3,The Git Up,Blanco Brown,60,The Git Up,2,0.847,0.678,-8.635,1,9,0.1090,0.06690,0.000000,0.2740,0.811,97.984,4,200594
4,Say Hey (I Love You),Michael Franti & Spearhead,58,All Rebel Rockers,0,0.738,0.983,-4.374,0,5,0.0855,0.03800,0.000006,0.1830,0.957,92.998,4,235760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,Skinny Legend Anthem,Ava Louise,32,Skinny Legend Anthem,50,0.845,0.518,-7.568,1,11,0.2990,0.07030,0.000000,0.1220,0.443,129.951,4,135993
219,Material Girl,Madonna,77,Celebration (double disc version),78,0.742,0.883,-3.419,1,0,0.0329,0.33300,0.000008,0.0964,0.978,136.506,4,240280
220,I Wish - Radio Edit,Skee-Lo,51,I Wish,63,0.715,0.738,-10.139,1,7,0.1570,0.00826,0.000000,0.2600,0.573,97.877,4,252307
221,Oh No I Got a Disease,Buss Crew,11,Oh No I Got a Disease,26,0.649,0.735,-4.365,0,10,0.7300,0.14600,0.000000,0.1240,0.845,86.704,5,134769
222,Woahh,Jufu,31,Woahh,22,0.749,0.283,-12.368,0,0,0.3280,0.61800,0.000004,0.0825,0.269,142.046,4,172888